inherit_from:
  - rubocop/gds-ruby-styleguide.yml
  - rubocop/other-lint.yml
  - rubocop/other-rails.yml
  - rubocop/other-style.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
