FORMAT: 1A

# Defence Request App Internal API
Defence Request Rota App Internal APIs

## Authorization
Currently, endpoints on the Rota App are not behind authorization. This will be changed in future using [Client Credentials Flow](https://github.com/doorkeeper-gem/doorkeeper/wiki/Client-Credentials-flow).

# Group API Root [/]

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body.

It is recommended to follow the “url” link values, [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve resources. Instead of constructing your own URLs, to keep your client decoupled from implementation details. We will use link values for all collection responses.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "on_duty_url": "/api/v1/on_duty_firm"
        }

# Group On Duty Firm

## On Duty [/api/v1/on_duty_firm?location_uid=xxx&time=2015-01-01T00:00:00+00:00]

This endpoint returns the Organisation UID for the firm which is on duty at the location and time provided.

When multiple consecutive calls are made to this endpoint, a different `organisation_uid` may be returned each time.
This is to ensure that requests are allocated fairly between each law firm if multiple firms are on duty at the same place at the same time.

The endpoint returns `nil` if there is no-one on duty at that time and location.

### Get firms on duty [GET]
+ Request

    + Headers

            Accept: application/json

+ Parameters
    + location_uid (uuid, required) - Location UID to query
    + time (string, required) - Time to query, in ISO8601 format


+ Response 200 (application/json)

        {
            "organisation_uid:" "b90f3c53-f511-4658-ad89-50ab9978d418"
        }

+ Response 200 (application/json)

        {
            "organisation_uid:" nil
        }
