default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch("LAA_ROTA_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("LAA_ROTA_DATABASE_PASSWORD", nil) %>
  username: <%= ENV.fetch("LAA_ROTA_DATABASE_USERNAME", nil) %>
  pool: <%= ENV.fetch("LAA_ROTA_DATABASE_POOL", 5) %>

development:
  <<: *default
  database: laa-rota_development

test:
  <<: *default
  database: laa-rota_test

production:
  <<: *default
  database: laa-rota_production
