default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DEFENCE_REQUEST_SERVICE_ROTA_DATABASE_DATABASE", nil) %>
  host: <%= ENV.fetch("DEFENCE_REQUEST_SERVICE_ROTA_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("DEFENCE_REQUEST_SERVICE_ROTA_DATABASE_PASSWORD", nil) %>
  username: <%= ENV.fetch("DEFENCE_REQUEST_SERVICE_ROTA_DATABASE_USERNAME", nil) %>
  pool: <%= ENV.fetch("DEFENCE_REQUEST_SERVICE_ROTA_DATABASE_POOL", 5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
