rails:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  force_ssl: <%= ENV.fetch("FORCE_SSL", true) %>

dsds:
  app_title: Defence Request Service Duty Rota

devise:
  key: <%= ENV.fetch('DEVISE_KEY') %>
  salt: <%= ENV.fetch('DEVISE_SALT') %>
  session_timeout: <%= ENV.fetch('SESSION_TIMEOUT_MINUTES', 60) %>

authentication:
  site_url: <%= ENV.fetch('AUTHENTICATION_SITE_URL') %>
  redirect_uri: <%= ENV.fetch('AUTHENTICATION_REDIRECT_URI') %>
  token_info_uri: <%= ENV.fetch('AUTHENTICATION_SITE_URL') %>/oauth/token/info
  application_id: <%= ENV.fetch('AUTHENTICATION_APPLICATION_ID') %>
  application_secret: <%= ENV.fetch('AUTHENTICATION_APPLICATION_SECRET') %>

bank_holidays:
  file_location: <%= ENV.fetch('BANK_HOLIDAYS_FILE', Rails.root.join("data", "bank_holidays.ics")) %>

aws:
  region: <%= ENV.fetch("AWS_REGION") %>
  s3_asset_bucket_name: <%= ENV.fetch("AWS_S3_ASSET_BUCKET_NAME") %>

sentry:
  # Note that this should only be set to false if you absolutely dont care
  # about the security of your environment. This makes error logging vulnerable
  # to man-in-the-middle attacks.
  ssl_verification: <%= ENV.fetch("SENTRY_SSL_VERIFICATION", true) %>

action_mailer:
  default_url_options:
    host: <%= ENV.fetch('MAILER_DEFAULT_URL_HOST') %>
    port: <%= ENV.fetch('MAILER_DEFAULT_URL_PORT') %>
    protocol: <%= ENV.fetch('MAILER_DEFAULT_URL_PROTOCOL') %>
  smtp_settings:
    address: smtp.sendgrid.net
    port: 587
    domain: em.email.dsds.dsd.io
    authentication: plain
    user_name: <%= ENV.fetch('MAILER_SMTP_USER_NAME') %>
    password: <%= ENV.fetch('MAILER_SMTP_PASSWORD') %>
    enable_starttls_auto: true