rails:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  force_ssl: <%= ENV.fetch("FORCE_SSL", true) %>

dsds:
  app_title: Defence Request Service Duty Rota

authentication:
  site_url: <%= ENV.fetch('AUTHENTICATION_SITE_URL') %>
  redirect_uri: <%= ENV.fetch('AUTHENTICATION_REDIRECT_URI') %>
  application_id: <%= ENV.fetch('AUTHENTICATION_APPLICATION_ID') %>
  application_secret: <%= ENV.fetch('AUTHENTICATION_APPLICATION_SECRET') %>
