#!/bin/bash
set -e

exec 2>&1
export HOME=/usr/src/app
export WEBUSER=www-data
export WEBGROUP=www-data

cd $HOME
chown -R $WEBUSER:$WEBGROUP /usr/src/app

case ${DOCKER_STATE} in
migrate)
    echo "running migrate"
    bundle exec rake db:migrate
    ;;
seed)
    echo "dropping database and running seeds"
    bundle exec rake db:reset
    ;;
esac

exec chpst -u $WEBUSER:$WEBGROUP bundle exec unicorn -c config/unicorn.rb
